// Pronto

export const _id = (index: number) => `e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index}`;

export const _times = (index: number) =>
  // 'MM/DD/YYYY'
  [
    '08/08/2024',
    '08/09/2023',
    '03/12/2023',
    '09/01/2022',
    '06/23/2022',
    '02/29/2024',
    '05/14/2024',
    '01/13/2024',
    '06/22/2024',
    '10/05/2023',
    '07/11/2024',
    '05/22/2024',
    '03/29/2024',
    '08/29/2023',
    '11/19/2023',
    '10/24/2023',
    '12/02/2023',
    '02/13/2024',
    '09/19/2023',
    '04/17/2024',
    '12/18/2023',
    '06/27/2024',
    '10/19/2023',
    '08/09/2024',
    '29/11/2024',
  ][index];

export const _fullName = (index: number) =>
  [
    'Billy Stoltenberg',
    'Eloise Ebert',
    'Teresa Luettgen',
    'Salvador Mayert',
    'Dr. Guadalupe Rath',
    'Kelvin Pouros',
    'Thelma Langworth',
    'Kristen Wunsch',
    'Steve Welch',
    'Brian Jacobs',
    'Lillie Schultz',
    'Mr. Conrad Spinka',
    'Charlene Krajcik',
    'Kerry Kuhlman',
    'Betty Hammes',
    'Tony Paucek PhD',
    'Sherri Davis',
    'Angel Rolfson-Kulas',
    'Dr. Lee Doyle-Grant',
    'Cheryl Romaguera',
    'Billy Braun',
    'Adam Trantow',
    'Brandon Von',
    'Willis Ankunding',
  ][index];

export const _price = (index: number) =>
  [
    35.17, 57.22, 64.78, 50.79, 9.57, 61.46, 96.73, 63.04, 33.18, 36.3, 54.42, 20.52, 62.82, 19.96,
    25.93, 70.39, 23.11, 67.23, 14.31, 31.5, 26.72, 44.8, 37.87, 75.53,
  ][index];

export const _company = (index: number) =>
  [
    'Medhurst, Moore and Franey',
    'Hahn, Homenick and Lind',
    'Larkin LLC',
    'Stamm, Larson and Mertz',
    'Spencer, Raynor and Langosh',
    'Lehner - Feeney',
    'Leuschke, Harris and Kuhlman',
    'Gutmann - Kassulke',
    'Turcotte - Runolfsson',
    'Howe - Anderson',
    'Sipes - Yost',
    'Johns - Aufderhar',
    'Schmidt LLC',
    'Smitham - Gerlach',
    'Waelchi - VonRueden',
    'Padberg - Macejkovic',
    'Lemke - Ferry',
    'Koch and Sons',
    'Klein - Rolfson',
    'Weimann LLC',
    'White, Cassin and Goldner',
    'Mohr, Langworth and Hills',
    'Mitchell, Volkman and Prosacco',
    'Streich Group',
  ][index];

export const _boolean = (index: number) =>
  [
    true,
    false,
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
  ][index];

  export const _postTitles = (index: number) => 
    [
      'Modelos de Prevenção a Desastres Naturais em Goiás',
      'Trailer de Camping Inspirado no Futuro da Mobilidade Sustentável',
      'Design de Soluções para Crises Climáticas em Goiás',
      '✨ O Que Está Feito Está Feito: Análise dos Efeitos das Secas em Goiás ✨',
      'Mudanças Climáticas no Cerrado: Como Elas Afetam Goiás',
      'A Ação Climática e a Economia de Goiás',
      'Pesquisa sobre Contaminação do Solo em Áreas de Risco em Goiás',
      'Como Criar Projetos Sustentáveis para Comunidades Impactadas',
      '40 Fontes Gratuitas para Design de Projetos Climáticos',
      'Examinando a Evolução do Impacto Climático em Comunidades de Goiás',
      'Katie Griffin: A Arte de Sensibilizar sobre Mudanças Climáticas',
      'O Sonho Brasileiro Recontado pela Ação Climática em Goiás',
      'Design de Sistemas para Resiliência Climática',
      'CarZio: Como Aplicativos podem Ajudar na Logística durante Desastres',
      'Como Criar Soluções Climáticas Sustentáveis com Netlify, Gatsby e Fauna',
      'Tylko Organize com Facilidade: Design Sustentável para Goiás',
      'RAYO ?? Identidade Visual de um Festival de Arte e Sustentabilidade',
      'Anthony Burrill e Andrew Diprose discutem a Arte Climática em Goiás',
      'Dentro da Mente de um Especialista em Desastres Climáticos',
      'Análise de Portfólio: Soluções Criativas para Mudanças Climáticas',
      'Akkers van Margraten: Estudo sobre Desastres e Recuperação em Goiás',
      'Icone de Ticket Sustentável para Desastres Climáticos',
      'Aqui está um conceito de motocicleta Dyson que não "suga" o meio ambiente!',
      'Como Animar um SVG com Imagens de Fronteira Sustentáveis',
    ][index];

    export const _description = (index: number) =>
      [
        'O "Nagasaki Lander" é o nome registrado de uma série de bicicletas esportivas que começaram com o modelo ABC800J em 1984.',
        'Nova linha de camisas formais projetadas para manter você confortável durante as emergências climáticas.',
        'As soluções de calçados Andy são criadas pensando na durabilidade, adaptadas às necessidades climáticas e estilos mais sustentáveis.',
        'O Futebol é ótimo para treinamento e recreação, mas as condições climáticas extremas podem afetar os jogos.',
        'O novo modelo ABC 13 9370, com 8GB de RAM e 256GB de SSD, ajuda na coordenação de ações de resiliência climática.',
        'Calçados Andy foram projetados com durabilidade e tendências sustentáveis em mente.',
        'As luvas de goleiro Carbonite são ergonomicamente projetadas para proporcionar um ajuste confortável e ideal para desastres naturais.',
        'O mouse wireless Apollotech B340 oferece conectividade confiável, com bateria de 12 meses, adequado para o trabalho em resposta a desastres.',
        'O "Nagasaki Lander" é o nome registrado de uma série de bicicletas esportivas que começaram com o modelo ABC800J em 1984.',
        'O layout do automóvel consiste em um design com motor frontal, com transmissões montadas na parte traseira do motor para mobilidade sustentável.',
        'O layout do automóvel consiste em um design com motor frontal, com transmissões montadas na parte traseira do motor, promovendo eficiência em condições climáticas adversas.',
        'O mouse wireless Apollotech B340 oferece conectividade confiável, com bateria de 12 meses, perfeito para situações de emergência.',
        'Nova linha de camisas formais projetadas para conforto e estilo em regiões afetadas por desastres climáticos.',
        "A tecnologia de compressão de Boston aumenta a oxigenação muscular, essencial para respostas rápidas durante desastres.",
        'Nova linha de camisas formais projetadas para conforto e estilo, permitindo adaptação em tempos de crise climática.',
        'Calçados Andy são projetados com durabilidade e conforto para situações de emergência e desastres naturais.',
        'Calçados Andy são projetados com durabilidade e estilo, ideais para áreas afetadas por desastres climáticos.',
        'A linha de produtos Apple Naturalé usa ingredientes naturais, promovendo soluções sustentáveis para o enfrentamento das mudanças climáticas.',
        "A tecnologia de compressão de Boston melhora a oxigenação muscular, essencial para respostas rápidas durante desastres naturais.",
        'O novo modelo ABC 13 9370, 13,3 polegadas, com processador CoreA5-8250U e 8GB de RAM, oferece suporte em situações de emergência.',
        'O "Nagasaki Lander" é o nome registrado de uma série de bicicletas esportivas que começaram com o modelo ABC800J em 1984, ótimas para situações de emergência.',
        'Cadeira ergonômica executiva estofada em couro negro, confortável e ideal para longas horas de planejamento durante desastres climáticos.',
        'O futebol é uma atividade recreativa que pode ser impactada pela variação climática e pela escassez de recursos em Goiás.',
        'O layout do automóvel consiste em um design com motor frontal, ideal para situações de emergência com foco em mobilidade sustentável.',
      ][index];
    
